/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_dengjx_ffmpegstudy_TestActivity */

#ifndef _Included_com_example_dengjx_ffmpegstudy_TestActivity
#define _Included_com_example_dengjx_ffmpegstudy_TestActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_dengjx_ffmpegstudy_TestActivity
 * Method:    avformatinfo
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_dengjx_ffmpegstudy_TestActivity_avformatinfo
  (JNIEnv *, jobject);

/*
 * Class:     com_example_dengjx_ffmpegstudy_TestActivity
 * Method:    avcodecinfo
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_dengjx_ffmpegstudy_TestActivity_avcodecinfo
  (JNIEnv *, jobject);

/*
 * Class:     com_example_dengjx_ffmpegstudy_TestActivity
 * Method:    avfilterinfo
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_dengjx_ffmpegstudy_TestActivity_avfilterinfo
  (JNIEnv *, jobject);

/*
 * Class:     com_example_dengjx_ffmpegstudy_TestActivity
 * Method:    configurationinfo
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_dengjx_ffmpegstudy_TestActivity_configurationinfo
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
