/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_ffmpeg_command_FFmpegKit */

#ifndef _Included_com_example_ffmpeg_command_FFmpegKit
#define _Included_com_example_ffmpeg_command_FFmpegKit
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_ffmpeg_command_FFmpegKit
 * Method:    run
 * Signature: ([Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_example_ffmpeg_1command_FFmpegKit_run
  (JNIEnv *, jclass, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
